services:
  mongodb:
    image: docker.io/bitnami/mongodb:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/bitnami/mongodb
      - mongodb-log:/opt/bitnami/mongodb/logs
    networks:
      - bridgex-rag
    env_file:
      - ./.env
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2


    ## These Following Command Override Dosn't Work With Bitnami Images
    # command:
    #   - --storageEngine
    #   - wiredTiger
    #   - --auth
    #   - '--logpath'
    #   - '/var/log/mongodb/mongod.log'

    restart: always
  
networks:
  bridgex-rag:

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
