[project]
name = "Bridge-X-RAG"
version = "0.1.0"
description = "Bridge-X RAG application"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "fastapi[standard]>=0.115.8",
    "langchain>=0.3.19",
    "langchain-community>=0.3.18",
    "pydantic-settings>=2.8.0",
    "pymupdf>=1.25.3",
]
